package com.raishxn.divineforge.registry;

public enum DivineAbility {
    BOLD_AS_BRASS("Bold as Brass", "boldasbrass"),
    BOREAL_INSTINCT("Boreal Instinct", "borealinstinct"),
    CIRCUS_PROPS("Circus Props", "circusprops"),
    CLIMATE_CHANGE("Climate Change", "climatechange"),
    COPPER_STATE("Copper State", "copperstate"),
    COSMIC_PRESENCE("Cosmic Presence", "cosmicpresence"),
    COVER_ME_IN_DEBRIS("Cover me in Debris", "covermeindebris"),
    ENERGY_SHIELD("Energy Shield", "energyshield"),
    ESCAPE_VELOCITY("Escape Velocity", "escapevelocity"),
    FOOLS_GOLD("Fool's Gold", "foolsgold"),
    FOSSILIZE("Fossilize", "fossilize"),
    FROM_BEGINNING_TO_END("From Beginning to End", "frombeginningtoend"),
    FROST_HEAL("Frost Heal", "frostheal"),
    GEMSTONE("Gemstone", "gemstone"),
    GRACE_OF_THE_QILIN("Grace of the Qilin", "graceoftheqilin"),
    HEAVY_METAL("Heavy Metal", "heavymetal"),
    HYDROTHERMAL("Hydrothermal", "hydrothermal"),
    IGNATE("Ignate", "ignate"),
    IN_BLOOM("In Bloom", "inbloom"),
    ICE_AGE("Ice Age", "iceage"),
    IRRADIATE("Irradiate", "irradiate"),
    JAW_OF_THE_DRAGON("Jaw of the Dragon", "jawofthedragon"),
    LIGHT_SPEED("Light Speed", "lightspeed"),
    LOOKING_GLASS("Looking Glass", "lookingglass"),
    LUNAR_ECLIPSE("Lunar Eclipse", "lunareclipse"),
    MEDIC("Medic", "medic"),
    MIMICRY("Mimicry", "mimicry"),
    NINE_HEADS("Nine Heads", "nineheads"),
    OMNIPOTENT("Omnipotent", "omnipotent"),
    PERMAFROST("Permafrost", "permafrost"),
    REAPER("Reaper", "reaper"),
    ROTTEN("Rotten", "rotten"),
    SHINING_STAR("Shining Star", "shiningstar"),
    SOLAR_FLARE("Solar Flare", "solarflare"),
    SOLAR_ECLIPSE("Solar Eclipse", "solareclipse"),
    SOUL_EATER("Soul Eater", "souleater"),
    TIME_WARP("Time Warp", "timewarp"),
    UNDEAD("Undead", "undead"),
    VENOMOUS("Venomous", "venomous"),
    WIND_FORCE("Wind Force", "windforce"),
    ACCELERATION("Acceleration", "acceleration"),
    AFTERMATH("Aftermath", "aftermath"),
    ATOMIZATE("Atomizate", "atomizate"),
    BLOOD_LUST("Blood Lust", "bloodlust"),
    DEEP_FREEZE("Deep Freeze", "deepfreeze"),
    DISENCHANT("Disenchant", "disenchant"),
    ELEMENTALIST("Elementalist", "elementalist"),
    ENERGIZATE("Energizate", "energizate"),
    FALLOUT("Fallout", "fallout"),
    INFURIATE("Infuriate", "infuriate"),
    LAZY("Lazy", "lazy"),
    LEAD_SKIN("Lead Skin", "leadskin"),
    PETRIFY("Petrify", "petrify"),
    QUICK_CHARGE("Quick Charge", "quickcharge"),
    SHARP_CORAL("Sharp Coral", "sharpcoral"),
    SOUND_BOOST("Sound Boost", "soundboost"),
    STORMBRINGER("Stormbringer", "stormbringer"),
    CLOUD_BURST("Cloud Burst", "cloudburst"),
    DIRTY_POOL("Dirty Pool", "dirtypool"),
    DRAGON_ARMOR("Dragon Armor", "dragonarmor"),
    EQUALIZE("Equalize", "equalize"),
    HOLY_GUARD("Holy Guard", "holyguard"),
    JUNGLE_SPIRIT("Jungle Spirit", "junglespirit"),
    MAJESTIC_AURA("Majestic Aura", "majesticaura"),
    RAPTOR("Raptor", "raptor"),
    SCALATE("Scalate", "scalate"),
    SOLAR_PROMINENCE("Solar Prominence", "solarprominence"),
    SYNTHESIZER("Synthesizer", "synthesizer"),
    TRUE_DARK("True Dark", "truedark"),
    VIGOR("Vigor", "vigor"),
    WICKED_BLOW("Wicked Blow", "wickedblow")
    ,BOLDASBRASS("Boldasbrass", "boldasbrass"),
    BOREALINSTINCT("Borealinstinct", "borealinstinct"),
    CIRCUSPROPS("Circusprops", "circusprops"),
    CLIMATECHANGE("Climatechange", "climatechange"),
    COPPERSTATE("Copperstate", "copperstate"),
    COSICPRESENCE("Cosmicpresence", "cosmicpresence"),
    COVERMEINDEBRIS("Covermeindebris", "covermeindebris"),
    DIGITIZE("Digitize", "digitize"),
    ENERGYSHIELD("Energyshield", "energyshield"),
    ESCAPEVELOCITY("Escapevelocity", "escapevelocity"),
    FOOLSGOLD("Foolsgold", "foolsgold"),
    FROMBEGINNINGTOEND("Frombeginningtoend", "frombeginningtoend"),
    FROSTHEAL("Frostheal", "frostheal"),
    GUTTERMIND("Guttermind", "guttermind"),
    HAILWARNING("Hailwarning", "hailwarning"),
    HAZYSURGE("Hazysurge", "hazysurge"),
    INVIGORATE("Invigorate", "invigorate"),
    IRONWILL("Ironwill", "ironwill"),
    MAGICIANSHAT("Magicianshat", "magicianshat"),
    PRISMATICHE("Prismatichue", "prismatichue"),
    RADSIPPER("Radsipper", "radsipper"),
    RHYTHMGAME("Rhythmgame", "rhythmgame"),
    RIDERSYNDROME("Ridersyndrome", "ridersyndrome"),
    SILVERLINING("Silverlining", "silverlining"),
    SNOWYSURGE("Snowysurge", "snowysurge"),
    TERRORIZE("Terrorize", "terrorize"),
    UNSTABLE("Unstable", "unstable"),
    VIBRANTHUE("Vibranthue", "vibranthue"),
    WIZARDSTOME("Wizardstome", "wizardstome"),
    XENOFORCE("Xenoforce", "xenoforce"),
    CHOICEBREAKER("Choicebreaker", "choicebreaker"),
    MENTALIST("Mentalist", "mentalist"),
    MYTHEATER("Mytheater", "mytheater"),
    POLYMORPHISM("Polymorphism", "polymorphism"),
    SHAREDMONARCHY("Sharedmonarchy", "sharedmonarchy"),
    BLOODBATH("Bloodbath", "bloodbath"),
    BLOODLUST("Bloodlust", "bloodlust"),
    FEARMONGER("Fearmonger", "fearmonger"),
    FREEZEBODY("Freezebody", "freezebody"),
    HAUNT("Haunt", "haunt"),
    HEEHO("Heeho", "heeho"),
    ALLSEEING("Allseeing", "allseeing"),
    DESERTBODY("Desertbody", "desertbody"),
    FREESTYLE("Freestyle", "freestyle"),
    IAISLASH("Iaislash", "iaislash"),
    SIGNALBOOST("Signalboost", "signalboost"),
    STATICTOUCH("Statictouch", "statictouch"),
    SUDDENSEED("Suddenseed", "suddenseed"),
    SUPERNOVA("Supernova", "supernova"),
    PIELPUNICA("Pielpunica", "pielpunica"),
    OJOSPETREOS("Ojospetreos", "ojospetreos"),
    BUSYBEE("Busybee", "busybee"),
    CONFIDENT("Confident", "confident"),
    HEADACHE("Headache", "headache"),
    ROSESTHORNS("Rosesthorns", "rosesthorns"),
    SANDPIT("Sandpit", "sandpit"),
    WINDTURBINE("Windturbine", "windturbine"),
    AIRCONTROL("Aircontrol", "aircontrol"),
    AMALGAM("Amalgam", "amalgam"),
    AMBUSH("Ambush", "ambush"),
    BARBEDNEST("Barbednest", "barbednest"),
    CHARGEDWOOL("Chargedwool", "chargedwool"),
    COMPOSED("Composed", "composed"),
    CRYSTALCASE("Crystalcase", "crystalcase"),
    ELUSIVE("Elusive", "elusive"),
    FOULSHROUD("Foulshroud", "foulshroud"),
    FRUITRITION("Fruitrition", "fruitrition"),
    GLACIALIZE("Glacialize", "glacialize"),
    INSATIABLE("Insatiable", "insatiable"),
    LASERFOCUS("Laserfocus", "laserfocus"),
    LEVINSKIN("Levinskin", "levinskin"),
    LITHE("Lithe", "lithe"),
    LUCKYSTAR("Luckystar", "luckystar"),
    NEFARIOUS("Nefarious", "nefarious"),
    POWERFIST("Powerfist", "powerfist"),
    REGALIA("Regalia", "regalia"),
    RESOLUTE("Resolute", "resolute"),
    SIEGEDRIVE("Siegedrive", "siegedrive"),
    SKY_SCOURGE("Skyscourge", "skyscourge"),
    SPECIALIST("Specialist", "specialist"),
    TACTICIAN("Tactician", "tactician"),
    VISIONARY("Visionary", "visionary"),
    BLACKHOLE("Blackhole", "blackhole"),
    COLDWAVE("Coldwave", "coldwave"),
    DEEPSLEEP("Deepsleep", "deepsleep"),
    EXPLODE("Explode", "explode"),
    FRIGHTEN("Frighten", "frighten"),
    SPRINT("Sprint", "sprint"),
    TENACITY("Tenacity", "tenacity"),
    ABSOLUTION("Absolution", "absolution"),
    AMPLIFIER("Amplifier", "amplifier"),
    ATHENIAN("Athenian", "athenian"),
    CASTLEMOAT("Castlemoat", "castlemoat"),
    CHLOROFURY("Chlorofury", "chlorofury"),
    EVENTHORIZON("Eventhorizon", "eventhorizon"),
    FOUNDRY("Foundry", "foundry"),
    HELIOPHOBIA("Heliophobia", "heliophobia"),
    HUBRIS("Hubris", "hubris"),
    ICE_CLEATS("Icecleats", "icecleats"),
    INTOXICATE("Intoxicate", "intoxicate"),
    IRRELEPHANT("Irrelephant", "irrelephant"),
    NOCTEM("Noctem", "noctem"),
    OMNITYPE("Omnitype", "omnitype"),
    PENDULUM("Pendulum", "pendulum"),
    PHOTOTROPH("Phototroph", "phototroph"),
    PRISM_GUARD("Prismguard", "prismguard"),
    PSYCHOCALL("Psychocall", "psychocall"),
    SHADOWCALL("Shadowcall", "shadowcall"),
    SHADOWDANCE("Shadowdance", "shadowdance"),
    SHADOWSYNERGY("Shadowsynergy", "shadowsynergy"),
    SLEET("Sleet", "sleet"),
    SPECTRALJAWS("Spectraljaws", "spectraljaws"),
    SPEEDSWAP("Speedswap", "speedswap"),
    SPIRITCALL("Spiritcall", "spiritcall"),
    VAMPIRIC("Vampiric", "vampiric"),
    ALCHEMICPOWER("Alchemicpower", "alchemicpower"),
    BADCOMPANY("Badcompany", "badcompany"),
    BLAZINGSOUL("Blazingsoul", "blazingsoul"),
    BLUBBERDEFENSE("Blubberdefense", "blubberdefense"),
    CASHSPLASH("Cashsplash", "cashsplash"),
    FELINEPROWESS("Felineprowess", "felineprowess"),
    ORAORAORAORA("Oraoraoraora", "oraoraoraora"),
    SELFSUFFICIENT("Selfsufficient", "selfsufficient"),
    STRIKER("Striker", "striker"),
    ADRENALINE("Adrenaline", "adrenaline"),
    ALLURE("Allure", "allure"),
    BRAVEHEART("Braveheart", "braveheart"),
    CONDITIONING("Conditioning", "conditioning"),
    CONTENT("Content", "content"),
    CONUNDRUM("Conundrum", "conundrum"),
    ECCENTRIC("Eccentric", "eccentric"),
    FEEDBACK("Feedback", "feedback"),
    FEISTY("Feisty", "feisty"),
    FORAGE("Forage", "forage"),
    HIGHNOON("Highnoon", "highnoon"),
    ICESLICK("Iceslick", "iceslick"),
    IRONJAW("Ironjaw", "ironjaw"),
    ORBITALTIDE("Orbitaltide", "orbitaltide"),
    PERFORATE("Perforate", "perforate"),
    POLLUTION("Pollution", "pollution"),
    PSYCHOUT("Psychout", "psychout"),
    REACTIVESHIELDING("Reactiveshielding", "reactiveshielding"),
    SCAVENGER("Scavenger", "scavenger"),
    SIPHON("Siphon", "siphon"),
    STUBBORN("Stubborn", "stubborn"),
    SUNBATHE("Sunbathe", "sunbathe"),
    BLOODTHIRST("Bloodthirst", "bloodthirst"),
    BOUNCY("Bouncy", "bouncy"),
    FLAMEEATER("Flameeater", "flameeater"),
    LUNARDIFFUSE("Lunardiffuse", "lunardiffuse"),
    SANDMAN("Sandman", "sandman"),
    SCARECROW("Scarecrow", "scarecrow"),
    SOLARDIFFUSE("Solardiffuse", "solardiffuse"),
    ABSOLUTEZERO("Absolutezero", "absolutezero"),
    ANCIENTBODY("Ancientbody", "ancientbody"),
    ARCANUM("Arcanum", "arcanum"),
    ARENABLOOM("Arenabloom", "arenabloom"),
    ARENACURSE("Arenacurse", "arenacurse"),
    BLOOMSPRING("Bloomspring", "bloomspring"),
    BUBBLEHELM("Bubblehelm", "bubblehelm"),
    CARBONCAPTURE("Carboncapture", "carboncapture"),
    CHAKRA("Chakra", "chakra"),
    CONDENSATION("Condensation", "condensation"),
    CONTAMINATION("Contamination", "contamination"),
    DUSTDEVIL("Dustdevil", "dustdevil"),
    DROUGHTPROOF("Droughtproof", "droughtproof"),
    DRUIDRY("Druidry", "druidry"),
    ECHOLOCATION("Echolocation", "echolocation"),
    ENERGIZER("Energizer", "energizer"),
    FERROFLUX("Ferroflux", "ferroflux"),
    FIELDWORKER("Fieldworker", "fieldworker"),
    FOIL("Foil", "foil"),
    FORKED("Forked", "forked"),
    GLACIALARMOR("Glacialarmor", "glacialarmor"),
    GRAVITYSLING("Gravitysling", "gravitysling"),
    HAUNTING("Haunting", "haunting"),
    HAYFEVER("Hayfever", "hayfever"),
    HYDROPHOBIC("Hydrophobic", "hydrophobic"),
    INCANTATION("Incantation", "incantation"),
    MASTERINSTINCT("Masterinstinct", "masterinstinct"),
    NASTYWEBBING("Nastywebbing", "nastywebbing"),
    NESTING("Nesting", "nesting"),
    ROOTCONTROL("Rootcontrol", "rootcontrol"),
    SEANCE("Seance", "seance"),
    SECRETION("Secretion", "secretion"),
    STANDOFF("Standoff", "standoff"),
    STORMFRONT("Stormfront", "stormfront"),
    SURVEILLANCE("Surveillance", "surveillance"),
    TOBE("Tobe", "tobe"),
    TRANSCENDENCE("Transcendence", "transcendence"),
    TRUMPETWEEVIL("Trumpetweevil", "trumpetweevil"),
    VEGETATE("Vegetate", "vegetate"),
    WARPMIST("Warpmist", "warpmist"),
    ACCELERATION_2("Acceleration_2", "acceleration"),
    ATOMIZATE_2("Atomizate_2", "atomizate"),
    CHERNOBYL("Chernobyl", "chernobyl"),
    DEEPFREEZE_2("Deepfreeze_2", "deepfreeze"),
    DISENCHANT_2("Disenchant_2", "disenchant"),
    ENERGIZATE_2("Energizate_2", "energizate"),
    INFURIATE_2("Infuriate_2", "infuriate"),
    LAZY_2("Lazy_2", "lazy"),
    LEADSKIN_2("Leadskin_2", "leadskin"),
    PETRIFY_2("Petrify_2", "petrify"),
    QUICKCHARGE_2("Quickcharge_2", "quickcharge"),
    SHARPCORAL_2("Sharpcoral_2", "sharpcoral"),
    SOUNDBOOST_2("Soundboost_2", "soundboost"),
    STORMBRINGER_2("Stormbringer_2", "stormbringer"),
    CLOUDBURST_2("Cloudburst_2", "cloudburst"),
    DIRTYPOOL_2("Dirtypool_2", "dirtypool"),
    DRAGONARMOR_2("Dragonarmor_2", "dragonarmor"),
    EQUALIZE_2("Equalize_2", "equalize"),
    HOLYGUARD_2("Holyguard_2", "holyguard"),
    JUNGLESPIRIT_2("Junglespirit_2", "junglespirit"),
    MAJESTICAURA_2("Majesticaura_2", "majesticaura"),
    RAPTOR_2("Raptor_2", "raptor"),
    SCALATE_2("Scalate_2", "scalate"),
    SOLARPROMINENCE_2("Solarprominence_2", "solarprominence"),
    SYNTHESIZER_2("Synthesizer_2", "synthesizer"),
    VOICETUNING("Voicetuning", "voicetuning");

    private final String displayName;
    private final String internalName;

    DivineAbility(String displayName, String internalName) {
        this.displayName = displayName;
        this.internalName = internalName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getInternalName() {
        return internalName;
    }

    // Método auxiliar para encontrar por nome interno (útil para compatibilidade se necessário)
    public static DivineAbility fromInternalName(String name) {
        for (DivineAbility ability : values()) {
            if (ability.internalName.equalsIgnoreCase(name)) {
                return ability;
            }
        }
        return null;
    }
}
